version: '3'

services:
  ml-ui:
    image: ml-ui
    ports:
      - "3000:3000"
    depends_on:
      - ml-api

  ml-api:
    image: ml-api
    ports:
      - "8000:80"
    environment:
      - DB_URL=./database/row.db
    volumes:
      - ./muslim-league-api/database:/code/database
