version: '3.7'

services:
  web-app:
    image: ball-app:latest
    ports:
      - "3000:80"
    depends_on:
      - core-api
  
  core-api:
    image: ball-core-api:latest
    ports:
      - "8080:8080"
    env_file:
      - ./muslim-league-core-api/.env